# xam
# ===
# ANSI CONSTANTS

const
  ANSI_RESET* = "\e[0m"
  ANSI_BOLD* = "\e[1m"
  ANSI_UNDERLINED* = "\e[4m"
  ANSI_REVERSED* = "\e[7m"
  ANSI_BLACK* = "\e[30m"
  ANSI_RED* = "\e[31m"
  ANSI_GREEN* = "\e[32m"
  ANSI_YELLOW* = "\e[33m"
  ANSI_BLUE* = "\e[34m"
  ANSI_MAGENTA* = "\e[35m"
  ANSI_CYAN* = "\e[36m"
  ANSI_WHITE* = "\e[37m"
  ANSI_BRIGHT_BLACK* = "\e[90m"
  ANSI_BRIGHT_RED* = "\e[91m"
  ANSI_BRIGHT_GREEN* = "\e[92m"
  ANSI_BRIGHT_YELLOW* = "\e[93m"
  ANSI_BRIGHT_BLUE* = "\e[94m"
  ANSI_BRIGHT_MAGENTA* = "\e[95m"
  ANSI_BRIGHT_CYAN* = "\e[96m"
  ANSI_BRIGHT_WHITE* = "\e[97m"
  ANSI_BG_BLACK* = "\e[40m"
  ANSI_BG_RED* = "\e[41m"
  ANSI_BG_GREEN* = "\e[42m"
  ANSI_BG_YELLOW* = "\e[43m"
  ANSI_BG_BLUE* = "\e[44m"
  ANSI_BG_MAGENTA* = "\e[45m"
  ANSI_BG_CYAN* = "\e[46m"
  ANSI_BG_WHITE* = "\e[47m"
  ANSI_BG_BRIGHT_BLACK* = "\e[100m"
  ANSI_BG_BRIGHT_RED* = "\e[101m"
  ANSI_BG_BRIGHT_GREEN* = "\e[102m"
  ANSI_BG_BRIGHT_YELLOW* = "\e[103m"
  ANSI_BG_BRIGHT_BLUE* = "\e[104m"
  ANSI_BG_BRIGHT_MAGENTA* = "\e[105m"
  ANSI_BG_BRIGHT_CYAN* = "\e[106m"
  ANSI_BG_BRIGHT_WHITE* = "\e[107m"

