# xam
# ===
# CHARS CONSTANTS

const
  # SYMBOLS  
  CHARS_TAB*: char = '\t'
  CHARS_LF*: char = '\n'
  CHARS_CR*: char = '\r'
  CHARS_SPACE*: char = ' '
  CHARS_EQUAL*: char = '='
  CHARS_NUMERAL*: char = '#'
  CHARS_PIPE*: char = '|'
  CHARS_MINUS*: char = '-'
  CHARS_PLUS*: char = '+'
  CHARS_PERCENT*: char = '%'
  CHARS_DOLLAR*: char = '$'
  CHARS_SLASH*: char = '/'
  CHARS_BACKSLASH*: char = '\\'
  CHARS_AMPERSAND*: char = '&'
  CHARS_ASTERISK*: char = '*'
  CHARS_UNDERSCORE*: char = '_'
  CHARS_COLON*: char = ':'
  CHARS_SEMICOLON*: char = ';'
  CHARS_COMMA*: char = ','
  CHARS_PERIOD*: char = '.'
  CHARS_APOSTROPHE*: char = '\''
  CHARS_QUOTE*: char = '\"'
  CHARS_CARET*: char = '^'
  CHARS_TILDE*: char = '~'
  CHARS_AT*: char = '@'
  CHARS_EXCLAMATION*: char = '!'
  CHARS_QUESTION*: char = '?'
  CHARS_INVERTED_EXCLAMATION*: char = "¡"[0]
  CHARS_INVERTED_QUESTION*: char = "¿"[0]
  CHARS_DEGREE*: char = "°"[0]
  CHARS_COPYRIGHT*: char = "©"[0]
  CHARS_REGISTERED*: char = "®"[0]
  CHARS_TRADEMARK*: char = "™"[0]
  CHARS_BULLET*: char = "•"[0]
  CHARS_PILCROW*: char = '\20' #'¶'
  CHARS_SECTION*: char = '\21' #'§'
  CHARS_MINOR*: char = '<'
  CHARS_MAJOR*: char = '>'
  CHARS_BRACES_OPEN*: char = '{'
  CHARS_BRACES_CLOSE*: char = '}'
  CHARS_BRACKETS_OPEN*: char = '['
  CHARS_BRACKETS_CLOSE*: char = ']'
  CHARS_PARENTHESES_OPEN*: char = '('
  CHARS_PARENTHESES_CLOSE*: char = ')'
  
  # NUMBERS
  CHARS_NUMBER_ZERO*: char = '0'
  CHARS_NUMBER_ONE*: char = '1'
  CHARS_NUMBER_TWO*: char = '2'
  CHARS_NUMBER_THREE*: char = '3'
  CHARS_NUMBER_FOUR*: char = '4'
  CHARS_NUMBER_FIVE*: char = '5'
  CHARS_NUMBER_SIX*: char = '6'
  CHARS_NUMBER_SEVEN*: char = '7'
  CHARS_NUMBER_EIGHT*: char = '8'
  CHARS_NUMBER_NINE*: char = '9'
  
  # UPPERCASE LETTERS
  CHARS_UPPERCASE_A*: char = 'A'
  CHARS_UPPERCASE_B*: char = 'B'
  CHARS_UPPERCASE_C*: char = 'C'
  CHARS_UPPERCASE_D*: char = 'D'
  CHARS_UPPERCASE_E*: char = 'E'
  CHARS_UPPERCASE_F*: char = 'F'
  CHARS_UPPERCASE_G*: char = 'G'
  CHARS_UPPERCASE_H*: char = 'H'
  CHARS_UPPERCASE_I*: char = 'I'
  CHARS_UPPERCASE_J*: char = 'J'
  CHARS_UPPERCASE_K*: char = 'K'
  CHARS_UPPERCASE_L*: char = 'L'
  CHARS_UPPERCASE_M*: char = 'M'
  CHARS_UPPERCASE_N*: char = 'N'
  CHARS_UPPERCASE_O*: char = 'O'
  CHARS_UPPERCASE_P*: char = 'P'
  CHARS_UPPERCASE_Q*: char = 'Q'
  CHARS_UPPERCASE_R*: char = 'R'
  CHARS_UPPERCASE_S*: char = 'S'
  CHARS_UPPERCASE_T*: char = 'T'
  CHARS_UPPERCASE_U*: char = 'U'
  CHARS_UPPERCASE_V*: char = 'V'
  CHARS_UPPERCASE_W*: char = 'W'
  CHARS_UPPERCASE_X*: char = 'X'
  CHARS_UPPERCASE_Y*: char = 'Y'
  CHARS_UPPERCASE_Z*: char = 'Z'
  
  # LOWERCASE LETTERS
  CHARS_LOWERCASE_A*: char = 'a'
  CHARS_LOWERCASE_B*: char = 'b'
  CHARS_LOWERCASE_C*: char = 'c'
  CHARS_LOWERCASE_D*: char = 'd'
  CHARS_LOWERCASE_E*: char = 'e'
  CHARS_LOWERCASE_F*: char = 'f'
  CHARS_LOWERCASE_G*: char = 'g'
  CHARS_LOWERCASE_H*: char = 'h'
  CHARS_LOWERCASE_I*: char = 'i'
  CHARS_LOWERCASE_J*: char = 'j'
  CHARS_LOWERCASE_K*: char = 'k'
  CHARS_LOWERCASE_L*: char = 'l'
  CHARS_LOWERCASE_M*: char = 'm'
  CHARS_LOWERCASE_N*: char = 'n'
  CHARS_LOWERCASE_O*: char = 'o'
  CHARS_LOWERCASE_P*: char = 'p'
  CHARS_LOWERCASE_Q*: char = 'q'
  CHARS_LOWERCASE_R*: char = 'r'
  CHARS_LOWERCASE_S*: char = 's'
  CHARS_LOWERCASE_T*: char = 't'
  CHARS_LOWERCASE_U*: char = 'u'
  CHARS_LOWERCASE_V*: char = 'v'
  CHARS_LOWERCASE_W*: char = 'w'
  CHARS_LOWERCASE_X*: char = 'x'
  CHARS_LOWERCASE_Y*: char = 'y'
  CHARS_LOWERCASE_Z*: char = 'z'
