# xam
# ===
# HTML COLOURS CONSTANTS

const
  HTML_COLORS_MAROON*: string = "#800000"
  HTML_COLORS_DARK_RED*: string = "#8B0000"
  HTML_COLORS_BROWN*: string = "#A52A2A"
  HTML_COLORS_FIREBRICK*: string = "#B22222"
  HTML_COLORS_CRIMSON*: string = "#DC143C"
  HTML_COLORS_RED*: string = "#FF0000"
  HTML_COLORS_TOMATO*: string = "#FF6347"
  HTML_COLORS_CORAL*: string = "#FF7F50"
  HTML_COLORS_INDIAN_RED*: string = "#CD5C5C"
  HTML_COLORS_LIGHT_CORAL*: string = "#F08080"
  HTML_COLORS_DARK_SALMON*: string = "#E9967A"
  HTML_COLORS_SALMON*: string = "#FA8072"
  HTML_COLORS_LIGHT_SALMON*: string = "#FFA07A"
  HTML_COLORS_ORANGE_RED*: string = "#FF4500"
  HTML_COLORS_DARK_ORANGE*: string = "#FF8C00"
  HTML_COLORS_ORANGE*: string = "#FFA500"
  HTML_COLORS_GOLD*: string = "#FFD700"
  HTML_COLORS_DARK_GOLDEN_ROD*: string = "#B8860B"
  HTML_COLORS_GOLDEN_ROD*: string = "#DAA520"
  HTML_COLORS_PALE_GOLDEN_ROD*: string = "#EEE8AA"
  HTML_COLORS_DARK_KHAKI*: string = "#BDB76B"
  HTML_COLORS_KHAKI*: string = "#F0E68C"
  HTML_COLORS_OLIVE*: string = "#808000"
  HTML_COLORS_YELLOW*: string = "#FFFF00"
  HTML_COLORS_YELLOW_GREEN*: string = "#9ACD32"
  HTML_COLORS_DARK_OLIVE_GREEN*: string = "#556B2F"
  HTML_COLORS_OLIVE_DRAB*: string = "#6B8E23"
  HTML_COLORS_LAWN_GREEN*: string = "#7CFC00"
  HTML_COLORS_CHART_REUSE*: string = "#7FFF00"
  HTML_COLORS_GREEN_YELLOW*: string = "#ADFF2F"
  HTML_COLORS_DARK_GREEN*: string = "#006400"
  HTML_COLORS_GREEN*: string = "#008000"
  HTML_COLORS_FOREST_GREEN*: string = "#228B22"
  HTML_COLORS_LIME*: string = "#00FF00"
  HTML_COLORS_LIME_GREEN*: string = "#32CD32"
  HTML_COLORS_LIGHT_GREEN*: string = "#90EE90"
  HTML_COLORS_PALE_GREEN*: string = "#98FB98"
  HTML_COLORS_DARK_SEA_GREEN*: string = "#8FBC8F"
  HTML_COLORS_MEDIUM_SPRING_GREEN*: string = "#00FA9A"
  HTML_COLORS_SPRING_GREEN*: string = "#00FF7F"
  HTML_COLORS_SEA_GREEN*: string = "#2E8B57"
  HTML_COLORS_MEDIUM_AQUA_MARINE*: string = "#66CDAA"
  HTML_COLORS_MEDIUM_SEA_GREEN*: string = "#3CB371"
  HTML_COLORS_LIGHT_SEA_GREEN*: string = "#20B2AA"
  HTML_COLORS_DARK_SLATE_GRAY*: string = "#2F4F4F"
  HTML_COLORS_TEAL*: string = "#008080"
  HTML_COLORS_DARK_CYAN*: string = "#008B8B"
  HTML_COLORS_AQUA*: string = "#00FFFF"
  HTML_COLORS_CYAN*: string = "#00FFFF"
  HTML_COLORS_LIGHT_CYAN*: string = "#E0FFFF"
  HTML_COLORS_DARK_TURQUOISE*: string = "#00CED1"
  HTML_COLORS_TURQUOISE*: string = "#40E0D0"
  HTML_COLORS_MEDIUM_TURQUOISE*: string = "#48D1CC"
  HTML_COLORS_PALE_TURQUOISE*: string = "#AFEEEE"
  HTML_COLORS_AQUA_MARINE*: string = "#7FFFD4"
  HTML_COLORS_POWDER_BLUE*: string = "#B0E0E6"
  HTML_COLORS_CADET_BLUE*: string = "#5F9EA0"
  HTML_COLORS_STEEL_BLUE*: string = "#4682B4"
  HTML_COLORS_CORN_FLOWER_BLUE*: string = "#6495ED"
  HTML_COLORS_DEEP_SKY_BLUE*: string = "#00BFFF"
  HTML_COLORS_DODGER_BLUE*: string = "#1E90FF"
  HTML_COLORS_LIGHT_BLUE*: string = "#ADD8E6"
  HTML_COLORS_SKY_BLUE*: string = "#87CEEB"
  HTML_COLORS_LIGHT_SKY_BLUE*: string = "#87CEFA"
  HTML_COLORS_MIDNIGHT_BLUE*: string = "#191970"
  HTML_COLORS_NAVY*: string = "#000080"
  HTML_COLORS_DARK_BLUE*: string = "#00008B"
  HTML_COLORS_MEDIUM_BLUE*: string = "#0000CD"
  HTML_COLORS_BLUE*: string = "#0000FF"
  HTML_COLORS_ROYAL_BLUE*: string = "#4169E1"
  HTML_COLORS_BLUE_VIOLET*: string = "#8A2BE2"
  HTML_COLORS_INDIGO*: string = "#4B0082"
  HTML_COLORS_DARK_SLATE_BLUE*: string = "#483D8B"
  HTML_COLORS_SLATE_BLUE*: string = "#6A5ACD"
  HTML_COLORS_MEDIUM_SLATE_BLUE*: string = "#7B68EE"
  HTML_COLORS_MEDIUM_PURPLE*: string = "#9370DB"
  HTML_COLORS_DARK_MAGENTA*: string = "#8B008B"
  HTML_COLORS_DARK_VIOLET*: string = "#9400D3"
  HTML_COLORS_DARK_ORCHID*: string = "#9932CC"
  HTML_COLORS_MEDIUM_ORCHID*: string = "#BA55D3"
  HTML_COLORS_PURPLE*: string = "#800080"
  HTML_COLORS_THISTLE*: string = "#D8BFD8"
  HTML_COLORS_PLUM*: string = "#DDA0DD"
  HTML_COLORS_VIOLET*: string = "#EE82EE"
  HTML_COLORS_MAGENTA*: string = "#FF00FF"
  HTML_COLORS_ORCHID*: string = "#DA70D6"
  HTML_COLORS_MEDIUM_VIOLET_RED*: string = "#C71585"
  HTML_COLORS_PALE_VIOLET_RED*: string = "#DB7093"
  HTML_COLORS_DEEP_PINK*: string = "#FF1493"
  HTML_COLORS_HOT_PINK*: string = "#FF69B4"
  HTML_COLORS_LIGHT_PINK*: string = "#FFB6C1"
  HTML_COLORS_PINK*: string = "#FFC0CB"
  HTML_COLORS_ANTIQUE_WHITE*: string = "#FAEBD7"
  HTML_COLORS_BEIGE*: string = "#F5F5DC"
  HTML_COLORS_BISQUE*: string = "#FFE4C4"
  HTML_COLORS_BLANCHED_ALMOND*: string = "#FFEBCD"
  HTML_COLORS_WHEAT*: string = "#F5DEB3"
  HTML_COLORS_CORN_SILK*: string = "#FFF8DC"
  HTML_COLORS_LEMON_CHIFFON*: string = "#FFFACD"
  HTML_COLORS_LIGHT_GOLDEN_ROD_YELLOW*: string = "#FAFAD2"
  HTML_COLORS_LIGHT_YELLOW*: string = "#FFFFE0"
  HTML_COLORS_SADDLE_BROWN*: string = "#8B4513"
  HTML_COLORS_SIENNA*: string = "#A0522D"
  HTML_COLORS_CHOCOLATE*: string = "#D2691E"
  HTML_COLORS_PERU*: string = "#CD853F"
  HTML_COLORS_SANDY_BROWN*: string = "#F4A460"
  HTML_COLORS_BURLY_WOOD*: string = "#DEB887"
  HTML_COLORS_TAN*: string = "#D2B48C"
  HTML_COLORS_ROSY_BROWN*: string = "#BC8F8F"
  HTML_COLORS_MOCCASIN*: string = "#FFE4B5"
  HTML_COLORS_NAVAJO_WHITE*: string = "#FFDEAD"
  HTML_COLORS_PEACH_PUFF*: string = "#FFDAB9"
  HTML_COLORS_MISTY_ROSE*: string = "#FFE4E1"
  HTML_COLORS_LAVENDER_BLUSH*: string = "#FFF0F5"
  HTML_COLORS_LINEN*: string = "#FAF0E6"
  HTML_COLORS_OLD_LACE*: string = "#FDF5E6"
  HTML_COLORS_PAPAYA_WHIP*: string = "#FFEFD5"
  HTML_COLORS_SEA_SHELL*: string = "#FFF5EE"
  HTML_COLORS_MINT_CREAM*: string = "#F5FFFA"
  HTML_COLORS_SLATE_GRAY*: string = "#708090"
  HTML_COLORS_LIGHT_SLATE_GRAY*: string = "#778899"
  HTML_COLORS_LIGHT_STEEL_BLUE*: string = "#B0C4DE"
  HTML_COLORS_LAVENDER*: string = "#E6E6FA"
  HTML_COLORS_FLORAL_WHITE*: string = "#FFFAF0"
  HTML_COLORS_ALICE_BLUE*: string = "#F0F8FF"
  HTML_COLORS_GHOST_WHITE*: string = "#F8F8FF"
  HTML_COLORS_HONEYDEW*: string = "#F0FFF0"
  HTML_COLORS_IVORY*: string = "#FFFFF0"
  HTML_COLORS_AZURE*: string = "#F0FFFF"
  HTML_COLORS_SNOW*: string = "#FFFAFA"
  HTML_COLORS_BLACK*: string = "#000000"
  HTML_COLORS_DIM_GRAY*: string = "#696969"
  HTML_COLORS_GRAY*: string = "#808080"
  HTML_COLORS_DARK_GRAY*: string = "#A9A9A9"
  HTML_COLORS_SILVER*: string = "#C0C0C0"
  HTML_COLORS_LIGHT_GRAY*: string = "#D3D3D3"
  HTML_COLORS_GAINSBORO*: string = "#DCDCDC"
  HTML_COLORS_WHITE_SMOKE*: string = "#F5F5F5"
  HTML_COLORS_WHITE*: string = "#FFFFFF"

const
  HTML_COLORS*: tuple = (
    MAROON: HTML_COLORS_MAROON,
    DARK_RED: HTML_COLORS_DARK_RED,
    BROWN: HTML_COLORS_BROWN,
    FIREBRICK: HTML_COLORS_FIREBRICK,
    CRIMSON: HTML_COLORS_CRIMSON,
    RED: HTML_COLORS_RED,
    TOMATO: HTML_COLORS_TOMATO,
    CORAL: HTML_COLORS_CORAL,
    INDIAN_RED: HTML_COLORS_INDIAN_RED,
    LIGHT_CORAL: HTML_COLORS_LIGHT_CORAL,
    DARK_SALMON: HTML_COLORS_DARK_SALMON,
    SALMON: HTML_COLORS_SALMON,
    LIGHT_SALMON: HTML_COLORS_LIGHT_SALMON,
    ORANGE_RED: HTML_COLORS_ORANGE_RED,
    DARK_ORANGE: HTML_COLORS_DARK_ORANGE,
    ORANGE: HTML_COLORS_ORANGE,
    GOLD: HTML_COLORS_GOLD,
    DARK_GOLDEN_ROD: HTML_COLORS_DARK_GOLDEN_ROD,
    GOLDEN_ROD: HTML_COLORS_GOLDEN_ROD,
    PALE_GOLDEN_ROD: HTML_COLORS_PALE_GOLDEN_ROD,
    DARK_KHAKI: HTML_COLORS_DARK_KHAKI,
    KHAKI: HTML_COLORS_KHAKI,
    OLIVE: HTML_COLORS_OLIVE,
    YELLOW: HTML_COLORS_YELLOW,
    YELLOW_GREEN: HTML_COLORS_YELLOW_GREEN,
    DARK_OLIVE_GREEN: HTML_COLORS_DARK_OLIVE_GREEN,
    OLIVE_DRAB: HTML_COLORS_OLIVE_DRAB,
    LAWN_GREEN: HTML_COLORS_LAWN_GREEN,
    CHART_REUSE: HTML_COLORS_CHART_REUSE,
    GREEN_YELLOW: HTML_COLORS_GREEN_YELLOW,
    DARK_GREEN: HTML_COLORS_DARK_GREEN,
    GREEN: HTML_COLORS_GREEN,
    FOREST_GREEN: HTML_COLORS_FOREST_GREEN,
    LIME: HTML_COLORS_LIME,
    LIME_GREEN: HTML_COLORS_LIME_GREEN,
    LIGHT_GREEN: HTML_COLORS_LIGHT_GREEN,
    PALE_GREEN: HTML_COLORS_PALE_GREEN,
    DARK_SEA_GREEN: HTML_COLORS_DARK_SEA_GREEN,
    MEDIUM_SPRING_GREEN: HTML_COLORS_MEDIUM_SPRING_GREEN,
    SPRING_GREEN: HTML_COLORS_SPRING_GREEN,
    SEA_GREEN: HTML_COLORS_SEA_GREEN,
    MEDIUM_AQUA_MARINE: HTML_COLORS_MEDIUM_AQUA_MARINE,
    MEDIUM_SEA_GREEN: HTML_COLORS_MEDIUM_SEA_GREEN,
    LIGHT_SEA_GREEN: HTML_COLORS_LIGHT_SEA_GREEN,
    DARK_SLATE_GRAY: HTML_COLORS_DARK_SLATE_GRAY,
    TEAL: HTML_COLORS_TEAL,
    DARK_CYAN: HTML_COLORS_DARK_CYAN,
    AQUA: HTML_COLORS_AQUA,
    CYAN: HTML_COLORS_CYAN,
    LIGHT_CYAN: HTML_COLORS_LIGHT_CYAN,
    DARK_TURQUOISE: HTML_COLORS_DARK_TURQUOISE,
    TURQUOISE: HTML_COLORS_TURQUOISE,
    MEDIUM_TURQUOISE: HTML_COLORS_MEDIUM_TURQUOISE,
    PALE_TURQUOISE: HTML_COLORS_PALE_TURQUOISE,
    AQUA_MARINE: HTML_COLORS_AQUA_MARINE,
    POWDER_BLUE: HTML_COLORS_POWDER_BLUE,
    CADET_BLUE: HTML_COLORS_CADET_BLUE,
    STEEL_BLUE: HTML_COLORS_STEEL_BLUE,
    CORN_FLOWER_BLUE: HTML_COLORS_CORN_FLOWER_BLUE,
    DEEP_SKY_BLUE: HTML_COLORS_DEEP_SKY_BLUE,
    DODGER_BLUE: HTML_COLORS_DODGER_BLUE,
    LIGHT_BLUE: HTML_COLORS_LIGHT_BLUE,
    SKY_BLUE: HTML_COLORS_SKY_BLUE,
    LIGHT_SKY_BLUE: HTML_COLORS_LIGHT_SKY_BLUE,
    MIDNIGHT_BLUE: HTML_COLORS_MIDNIGHT_BLUE,
    NAVY: HTML_COLORS_NAVY,
    DARK_BLUE: HTML_COLORS_DARK_BLUE,
    MEDIUM_BLUE: HTML_COLORS_MEDIUM_BLUE,
    BLUE: HTML_COLORS_BLUE,
    ROYAL_BLUE: HTML_COLORS_ROYAL_BLUE,
    BLUE_VIOLET: HTML_COLORS_BLUE_VIOLET,
    INDIGO: HTML_COLORS_INDIGO,
    DARK_SLATE_BLUE: HTML_COLORS_DARK_SLATE_BLUE,
    SLATE_BLUE: HTML_COLORS_SLATE_BLUE,
    MEDIUM_SLATE_BLUE: HTML_COLORS_MEDIUM_SLATE_BLUE,
    MEDIUM_PURPLE: HTML_COLORS_MEDIUM_PURPLE,
    DARK_MAGENTA: HTML_COLORS_DARK_MAGENTA,
    DARK_VIOLET: HTML_COLORS_DARK_VIOLET,
    DARK_ORCHID: HTML_COLORS_DARK_ORCHID,
    MEDIUM_ORCHID: HTML_COLORS_MEDIUM_ORCHID,
    PURPLE: HTML_COLORS_PURPLE,
    THISTLE: HTML_COLORS_THISTLE,
    PLUM: HTML_COLORS_PLUM,
    VIOLET: HTML_COLORS_VIOLET,
    MAGENTA: HTML_COLORS_MAGENTA,
    ORCHID: HTML_COLORS_ORCHID,
    MEDIUM_VIOLET_RED: HTML_COLORS_MEDIUM_VIOLET_RED,
    PALE_VIOLET_RED: HTML_COLORS_PALE_VIOLET_RED,
    DEEP_PINK: HTML_COLORS_DEEP_PINK,
    HOT_PINK: HTML_COLORS_HOT_PINK,
    LIGHT_PINK: HTML_COLORS_LIGHT_PINK,
    PINK: HTML_COLORS_PINK,
    ANTIQUE_WHITE: HTML_COLORS_ANTIQUE_WHITE,
    BEIGE: HTML_COLORS_BEIGE,
    BISQUE: HTML_COLORS_BISQUE,
    BLANCHED_ALMOND: HTML_COLORS_BLANCHED_ALMOND,
    WHEAT: HTML_COLORS_WHEAT,
    CORN_SILK: HTML_COLORS_CORN_SILK,
    LEMON_CHIFFON: HTML_COLORS_LEMON_CHIFFON,
    LIGHT_GOLDEN_ROD_YELLOW: HTML_COLORS_LIGHT_GOLDEN_ROD_YELLOW,
    LIGHT_YELLOW: HTML_COLORS_LIGHT_YELLOW,
    SADDLE_BROWN: HTML_COLORS_SADDLE_BROWN,
    SIENNA: HTML_COLORS_SIENNA,
    CHOCOLATE: HTML_COLORS_CHOCOLATE,
    PERU: HTML_COLORS_PERU,
    SANDY_BROWN: HTML_COLORS_SANDY_BROWN,
    BURLY_WOOD: HTML_COLORS_BURLY_WOOD,
    TAN: HTML_COLORS_TAN,
    ROSY_BROWN: HTML_COLORS_ROSY_BROWN,
    MOCCASIN: HTML_COLORS_MOCCASIN,
    NAVAJO_WHITE: HTML_COLORS_NAVAJO_WHITE,
    PEACH_PUFF: HTML_COLORS_PEACH_PUFF,
    MISTY_ROSE: HTML_COLORS_MISTY_ROSE,
    LAVENDER_BLUSH: HTML_COLORS_LAVENDER_BLUSH,
    LINEN: HTML_COLORS_LINEN,
    OLD_LACE: HTML_COLORS_OLD_LACE,
    PAPAYA_WHIP: HTML_COLORS_PAPAYA_WHIP,
    SEA_SHELL: HTML_COLORS_SEA_SHELL,
    MINT_CREAM: HTML_COLORS_MINT_CREAM,
    SLATE_GRAY: HTML_COLORS_SLATE_GRAY,
    LIGHT_SLATE_GRAY: HTML_COLORS_LIGHT_SLATE_GRAY,
    LIGHT_STEEL_BLUE: HTML_COLORS_LIGHT_STEEL_BLUE,
    LAVENDER: HTML_COLORS_LAVENDER,
    FLORAL_WHITE: HTML_COLORS_FLORAL_WHITE,
    ALICE_BLUE: HTML_COLORS_ALICE_BLUE,
    GHOST_WHITE: HTML_COLORS_GHOST_WHITE,
    HONEYDEW: HTML_COLORS_HONEYDEW,
    IVORY: HTML_COLORS_IVORY,
    AZURE: HTML_COLORS_AZURE,
    SNOW: HTML_COLORS_SNOW,
    BLACK: HTML_COLORS_BLACK,
    DIM_GRAY: HTML_COLORS_DIM_GRAY,
    GRAY: HTML_COLORS_GRAY,
    DARK_GRAY: HTML_COLORS_DARK_GRAY,
    SILVER: HTML_COLORS_SILVER,
    LIGHT_GRAY: HTML_COLORS_LIGHT_GRAY,
    GAINSBORO: HTML_COLORS_GAINSBORO,
    WHITE_SMOKE: HTML_COLORS_WHITE_SMOKE,
    WHITE: HTML_COLORS_WHITE
  )
