# xam
# ===
# HTML TAGS CONSTANTS

const
  HTML_TAGS_A* = "a"
  HTML_TAGS_ABBR* = "abbr"
  HTML_TAGS_ACRONYM* = "acronym"
  HTML_TAGS_ADDRESS* = "address"
  HTML_TAGS_APPLET* = "applet"
  HTML_TAGS_AREA* = "area"
  HTML_TAGS_ARTICLE* = "article"
  HTML_TAGS_ASIDE* = "aside"
  HTML_TAGS_AUDIO* = "audio"
  HTML_TAGS_B* = "b"
  HTML_TAGS_BASE* = "base"
  HTML_TAGS_BASEFONT* = "basefont"
  HTML_TAGS_BDI* = "bdi"
  HTML_TAGS_BDO* = "bdo"
  HTML_TAGS_BIG* = "big"
  HTML_TAGS_BLOCKQUOTE* = "blockquote"
  HTML_TAGS_BODY* = "body"
  HTML_TAGS_BR* = "br"
  HTML_TAGS_BUTTON* = "button"
  HTML_TAGS_CANVAS* = "canvas"
  HTML_TAGS_CAPTION* = "caption"
  HTML_TAGS_CENTER* = "center"
  HTML_TAGS_CITE* = "cite"
  HTML_TAGS_CODE* = "code"
  HTML_TAGS_COL* = "col"
  HTML_TAGS_COLGROUP* = "colgroup"
  HTML_TAGS_DATALIST* = "datalist"
  HTML_TAGS_DD* = "dd"
  HTML_TAGS_DEL* = "del"
  HTML_TAGS_DETAILS* = "details"
  HTML_TAGS_DFN* = "dfn"
  HTML_TAGS_DIALOG* = "dialog"
  HTML_TAGS_DIR* = "dir"
  HTML_TAGS_DIV* = "div"
  HTML_TAGS_DL* = "dl"
  HTML_TAGS_DT* = "dt"
  HTML_TAGS_EM* = "em"
  HTML_TAGS_EMBED* = "embed"
  HTML_TAGS_FIELDSET* = "fieldset"
  HTML_TAGS_FIGCAPTION* = "figcaption"
  HTML_TAGS_FIGURE* = "figure"
  HTML_TAGS_FONT* = "font"
  HTML_TAGS_FOOTER* = "footer"
  HTML_TAGS_FORM* = "form"
  HTML_TAGS_FRAME* = "frame"
  HTML_TAGS_FRAMESET* = "frameset"
  HTML_TAGS_H1* = "h1"
  HTML_TAGS_H2* = "h2"
  HTML_TAGS_H3* = "h3"
  HTML_TAGS_H4* = "h4"
  HTML_TAGS_H5* = "h5"
  HTML_TAGS_H6* = "h6"
  HTML_TAGS_HEAD* = "head"
  HTML_TAGS_HEADER* = "header"
  HTML_TAGS_HR* = "hr"
  HTML_TAGS_HTML* = "html"
  HTML_TAGS_I* = "i"
  HTML_TAGS_IFRAME* = "iframe"
  HTML_TAGS_IMG* = "img"
  HTML_TAGS_INPUT* = "input"
  HTML_TAGS_INS* = "ins"
  HTML_TAGS_KBD* = "kbd"
  HTML_TAGS_LABEL* = "label"
  HTML_TAGS_LEGEND* = "legend"
  HTML_TAGS_LI* = "li"
  HTML_TAGS_LINK* = "link"
  HTML_TAGS_MAIN* = "main"
  HTML_TAGS_MAP* = "map"
  HTML_TAGS_MARK* = "mark"
  HTML_TAGS_META* = "meta"
  HTML_TAGS_METER* = "meter"
  HTML_TAGS_NAV* = "nav"
  HTML_TAGS_NOFRAMES* = "noframes"
  HTML_TAGS_NOSCRIPT* = "noscript"
  HTML_TAGS_OBJECT* = "object"
  HTML_TAGS_OL* = "ol"
  HTML_TAGS_OPTGROUP* = "optgroup"
  HTML_TAGS_OPTION* = "option"
  HTML_TAGS_OUTPUT* = "output"
  HTML_TAGS_P* = "p"
  HTML_TAGS_PARAM* = "param"
  HTML_TAGS_PRE* = "pre"
  HTML_TAGS_PROGRESS* = "progress"
  HTML_TAGS_Q* = "q"
  HTML_TAGS_RP* = "rp"
  HTML_TAGS_RT* = "rt"
  HTML_TAGS_RUBY* = "ruby"
  HTML_TAGS_S* = "s"
  HTML_TAGS_SAMP* = "samp"
  HTML_TAGS_SCRIPT* = "script"
  HTML_TAGS_SECTION* = "section"
  HTML_TAGS_SELECT* = "select"
  HTML_TAGS_SMALL* = "small"
  HTML_TAGS_SOURCE* = "source"
  HTML_TAGS_SPAN* = "span"
  HTML_TAGS_STRIKE* = "strike"
  HTML_TAGS_STRONG* = "strong"
  HTML_TAGS_STYLE* = "style"
  HTML_TAGS_SUB* = "sub"
  HTML_TAGS_SUMMARY* = "summary"
  HTML_TAGS_SUP* = "sup"
  HTML_TAGS_TABLE* = "table"
  HTML_TAGS_TBODY* = "tbody"
  HTML_TAGS_TD* = "td"
  HTML_TAGS_TEXTAREA* = "textarea"
  HTML_TAGS_TFOOT* = "tfoot"
  HTML_TAGS_TH* = "th"
  HTML_TAGS_THEAD* = "thead"
  HTML_TAGS_TIME* = "time"
  HTML_TAGS_TITLE* = "title"
  HTML_TAGS_TR* = "tr"
  HTML_TAGS_TRACK* = "track"
  HTML_TAGS_TT* = "tt"
  HTML_TAGS_U* = "u"
  HTML_TAGS_UL* = "ul"
  HTML_TAGS_VAR* = "var"
  HTML_TAGS_VIDEO* = "video"
  HTML_TAGS_WBR* = "wbr"

const
  HTML_TAGS*: tuple = (
    A: HTML_TAGS_A,
    ABBR: HTML_TAGS_ABBR,
    ACRONYM: HTML_TAGS_ACRONYM,
    ADDRESS: HTML_TAGS_ADDRESS,
    APPLET: HTML_TAGS_APPLET,
    AREA: HTML_TAGS_AREA,
    ARTICLE: HTML_TAGS_ARTICLE,
    ASIDE: HTML_TAGS_ASIDE,
    AUDIO: HTML_TAGS_AUDIO,
    B: HTML_TAGS_B,
    BASE: HTML_TAGS_BASE,
    BASEFONT: HTML_TAGS_BASEFONT,
    BDI: HTML_TAGS_BDI,
    BDO: HTML_TAGS_BDO,
    BIG: HTML_TAGS_BIG,
    BLOCKQUOTE: HTML_TAGS_BLOCKQUOTE,
    BODY: HTML_TAGS_BODY,
    BR: HTML_TAGS_BR,
    BUTTON: HTML_TAGS_BUTTON,
    CANVAS: HTML_TAGS_CANVAS,
    CAPTION: HTML_TAGS_CAPTION,
    CENTER: HTML_TAGS_CENTER,
    CITE: HTML_TAGS_CITE,
    CODE: HTML_TAGS_CODE,
    COL: HTML_TAGS_COL,
    COLGROUP: HTML_TAGS_COLGROUP,
    DATALIST: HTML_TAGS_DATALIST,
    DD: HTML_TAGS_DD,
    DEL: HTML_TAGS_DEL,
    DETAILS: HTML_TAGS_DETAILS,
    DFN: HTML_TAGS_DFN,
    DIALOG: HTML_TAGS_DIALOG,
    DIR: HTML_TAGS_DIR,
    DIV: HTML_TAGS_DIV,
    DL: HTML_TAGS_DL,
    DT: HTML_TAGS_DT,
    EM: HTML_TAGS_EM,
    EMBED: HTML_TAGS_EMBED,
    FIELDSET: HTML_TAGS_FIELDSET,
    FIGCAPTION: HTML_TAGS_FIGCAPTION,
    FIGURE: HTML_TAGS_FIGURE,
    FONT: HTML_TAGS_FONT,
    FOOTER: HTML_TAGS_FOOTER,
    FORM: HTML_TAGS_FORM,
    FRAME: HTML_TAGS_FRAME,
    FRAMESET: HTML_TAGS_FRAMESET,
    H1: HTML_TAGS_H1,
    H2: HTML_TAGS_H2,
    H3: HTML_TAGS_H3,
    H4: HTML_TAGS_H4,
    H5: HTML_TAGS_H5,
    H6: HTML_TAGS_H6,
    HEAD: HTML_TAGS_HEAD,
    HEADER: HTML_TAGS_HEADER,
    HR: HTML_TAGS_HR,
    HTML: HTML_TAGS_HTML,
    I: HTML_TAGS_I,
    IFRAME: HTML_TAGS_IFRAME,
    IMG: HTML_TAGS_IMG,
    INPUT: HTML_TAGS_INPUT,
    INS: HTML_TAGS_INS,
    KBD: HTML_TAGS_KBD,
    LABEL: HTML_TAGS_LABEL,
    LEGEND: HTML_TAGS_LEGEND,
    LI: HTML_TAGS_LI,
    LINK: HTML_TAGS_LINK,
    MAIN: HTML_TAGS_MAIN,
    MAP: HTML_TAGS_MAP,
    MARK: HTML_TAGS_MARK,
    META: HTML_TAGS_META,
    METER: HTML_TAGS_METER,
    NAV: HTML_TAGS_NAV,
    NOFRAMES: HTML_TAGS_NOFRAMES,
    NOSCRIPT: HTML_TAGS_NOSCRIPT,
    OBJECT: HTML_TAGS_OBJECT,
    OL: HTML_TAGS_OL,
    OPTGROUP: HTML_TAGS_OPTGROUP,
    OPTION: HTML_TAGS_OPTION,
    OUTPUT: HTML_TAGS_OUTPUT,
    P: HTML_TAGS_P,
    PARAM: HTML_TAGS_PARAM,
    PRE: HTML_TAGS_PRE,
    PROGRESS: HTML_TAGS_PROGRESS,
    Q: HTML_TAGS_Q,
    RP: HTML_TAGS_RP ,
    RT: HTML_TAGS_RT ,
    RUBY: HTML_TAGS_RUBY,
    S: HTML_TAGS_S,
    SAMP: HTML_TAGS_SAMP,
    SCRIPT: HTML_TAGS_SCRIPT,
    SECTION: HTML_TAGS_SECTION,
    SELECT: HTML_TAGS_SELECT,
    SMALL: HTML_TAGS_SMALL, 
    SOURCE: HTML_TAGS_SOURCE,
    SPAN: HTML_TAGS_SPAN,
    STRIKE: HTML_TAGS_STRIKE,
    STRONG: HTML_TAGS_STRONG,
    STYLE: HTML_TAGS_STYLE, 
    SUB: HTML_TAGS_SUB,
    SUMMARY: HTML_TAGS_SUMMARY,
    SUP: HTML_TAGS_SUP,
    TABLE: HTML_TAGS_TABLE,
    TBODY: HTML_TAGS_TBODY,
    TD: HTML_TAGS_TD,
    TEXTAREA: HTML_TAGS_TEXTAREA,
    TFOOT: HTML_TAGS_TFOOT,
    TH: HTML_TAGS_TH,
    THEAD: HTML_TAGS_THEAD,
    TIME: HTML_TAGS_TIME,
    TITLE: HTML_TAGS_TITLE,
    TR: HTML_TAGS_TR,
    TRACK: HTML_TAGS_TRACK,
    TT: HTML_TAGS_TT,
    U: HTML_TAGS_U,
    UL: HTML_TAGS_UL,
    VAR: HTML_TAGS_VAR,
    VIDEO: HTML_TAGS_VIDEO,
    WBR: HTML_TAGS_WBR
  )
