# xam
# ===
# LANGUAGES CONSTANTS

# ISO-639-1 INTERNATIONAL LANGUAGE CODES

const LANGUAGE_CODES* = (
  AA: "aa",
  AB: "ab",
  AF: "af",
  AM: "am",
  AR: "ar",
  AR_AE: "ar-ae",
  AR_BH: "ar-bh",
  AR_DZ: "ar-dz",
  AR_EG: "ar-eg",
  AR_IQ: "ar-iq",
  AR_JO: "ar-jo",
  AR_KW: "ar-kw",
  AR_LB: "ar-lb",
  AR_LY: "ar-ly",
  AR_MA: "ar-ma",
  AR_OM: "ar-om",
  AR_QA: "ar-qa",
  AR_SA: "ar-sa",
  AR_SY: "ar-sy",
  AR_TN: "ar-tn",
  AR_YE: "ar-ye",
  AS: "as",
  AY: "ay",
  AZ: "az",
  BA: "ba",
  BE: "be",
  BG: "bg",
  BH: "bh",
  BI: "bi",
  BN: "bn",
  BO: "bo",
  BR: "br",
  CA: "ca",
  CO: "co",
  CS: "cs",
  CY: "cy",
  DA: "da",
  DE: "de",
  DE_AT: "de-at",
  DE_CH: "de-ch",
  DE_LI: "de-li",
  DE_LU: "de-lu",
  DIV: "div",
  DZ: "dz",
  EL: "el",
  EN: "en",
  EN_AU: "en-au",
  EN_BZ: "en-bz",
  EN_CA: "en-ca",
  EN_GB: "en-gb",
  EN_IE: "en-ie",
  EN_JM: "en-jm",
  EN_NZ: "en-nz",
  EN_PH: "en-ph",
  EN_TT: "en-tt",
  EN_US: "en-us",
  EN_ZA: "en-za",
  EN_ZW: "en-zw",
  EO: "eo",
  ES: "es",
  ES_AR: "es-ar",
  ES_BO: "es-bo",
  ES_CL: "es-cl",
  ES_CO: "es-co",
  ES_CR: "es-cr",
  ES_DO: "es-do",
  ES_EC: "es-ec",
  ES_ES: "es-es",
  ES_GT: "es-gt",
  ES_HN: "es-hn",
  ES_MX: "es-mx",
  ES_NI: "es-ni",
  ES_PA: "es-pa",
  ES_PE: "es-pe",
  ES_PR: "es-pr",
  ES_PY: "es-py",
  ES_SV: "es-sv",
  ES_US: "es-us",
  ES_UY: "es-uy",
  ES_VE: "es-ve",
  ET: "et",
  EU: "eu",
  FA: "fa",
  FI: "fi",
  FJ: "fj",
  FO: "fo",
  FR: "fr",
  FR_BE: "fr-be",
  FR_CA: "fr-ca",
  FR_CH: "fr-ch",
  FR_LU: "fr-lu",
  FR_MC: "fr-mc",
  FY: "fy",
  GA: "ga",
  GD: "gd",
  GL: "gl",
  GN: "gn",
  GU: "gu",
  HA: "ha",
  HE: "he",
  HI: "hi",
  HR: "hr",
  HU: "hu",
  HY: "hy",
  IA: "ia",
  ID: "id",
  IE: "ie",
  IK: "ik",
  IN: "in",
  IS: "is",
  IT: "it",
  IT_CH: "it-ch",
  IW: "iw",
  JA: "ja",
  JI: "ji",
  JW: "jw",
  KA: "ka",
  KK: "kk",
  KL: "kl",
  KM: "km",
  KN: "kn",
  KO: "ko",
  KOK: "kok",
  KS: "ks",
  KU: "ku",
  KY: "ky",
  KZ: "kz",
  LA: "la",
  LN: "ln",
  LO: "lo",
  LS: "ls",
  LT: "lt",
  LV: "lv",
  MG: "mg",
  MI: "mi",
  MK: "mk",
  ML: "ml",
  MN: "mn",
  MO: "mo",
  MR: "mr",
  MS: "ms",
  MT: "mt",
  MY: "my",
  NA: "na",
  NB_NO: "nb-no",
  NE: "ne",
  NL: "nl",
  NL_BE: "nl-be",
  NN_NO: "nn-no",
  NO: "no",
  OC: "oc",
  OM: "om",
  OR: "or",
  PA: "pa",
  PL: "pl",
  PS: "ps",
  PT: "pt",
  PT_BR: "pt-br",
  QU: "qu",
  RM: "rm",
  RN: "rn",
  RO: "ro",
  RO_MD: "ro-md",
  RU: "ru",
  RU_MD: "ru-md",
  RW: "rw",
  SA: "sa",
  SB: "sb",
  SD: "sd",
  SG: "sg",
  SH: "sh",
  SI: "si",
  SK: "sk",
  SL: "sl",
  SM: "sm",
  SN: "sn",
  SO: "so",
  SQ: "sq",
  SR: "sr",
  SS: "ss",
  ST: "st",
  SU: "su",
  SV: "sv",
  SV_FI: "sv-fi",
  SW: "sw",
  SX: "sx",
  SYR: "syr",
  TA: "ta",
  TE: "te",
  TG: "tg",
  TH: "th",
  TI: "ti",
  TK: "tk",
  TL: "tl",
  TN: "tn",
  TO: "to",
  TR: "tr",
  TS: "ts",
  TT: "tt",
  TW: "tw",
  UK: "uk",
  UR: "ur",
  US: "us",
  UZ: "uz",
  VI: "vi",
  VO: "vo",
  WO: "wo",
  XH: "xh",
  YI: "yi",
  YO: "yo",
  ZH: "zh",
  ZH_CN: "zh-cn",
  ZH_HK: "zh-hk",
  ZH_MO: "zh-mo",
  ZH_SG: "zh-sg",
  ZH_TW: "zh-tw",
  ZU: "zu"
)

# ISO-639-1 INTERNATIONAL LANGUAGE NAMES

const LANGUAGE_NAMES* = (
  AA: "Afar",
  AB: "Abkhazian",
  AF: "Afrikaans",
  AM: "Amharic",
  AR: "Arabic",
  AR_AE: "Arabic (U.A.E.)",
  AR_BH: "Arabic (Bahrain)",
  AR_DZ: "Arabic (Algeria)",
  AR_EG: "Arabic (Egypt)",
  AR_IQ: "Arabic (Iraq)",
  AR_JO: "Arabic (Jordan)",
  AR_KW: "Arabic (Kuwait)",
  AR_LB: "Arabic (Lebanon)",
  AR_LY: "Arabic (libya)",
  AR_MA: "Arabic (Morocco)",
  AR_OM: "Arabic (Oman)",
  AR_QA: "Arabic (Qatar)",
  AR_SA: "Arabic (Saudi Arabia)",
  AR_SY: "Arabic (Syria)",
  AR_TN: "Arabic (Tunisia)",
  AR_YE: "Arabic (Yemen)",
  AS: "Assamese",
  AY: "Aymara",
  AZ: "Azeri",
  BA: "Bashkir",
  BE: "Belarusian",
  BG: "Bulgarian",
  BH: "Bihari",
  BI: "Bislama",
  BN: "Bengali",
  BO: "Tibetan",
  BR: "Breton",
  CA: "Catalan",
  CO: "Corsican",
  CS: "Czech",
  CY: "Welsh",
  DA: "Danish",
  DE: "German",
  DE_AT: "German (Austria)",
  DE_CH: "German (Switzerland)",
  DE_LI: "German (Liechtenstein)",
  DE_LU: "German (Luxembourg)",
  DIV: "Divehi",
  DZ: "Bhutani",
  EL: "Greek",
  EN: "English",
  EN_AU: "English (Australia)",
  EN_BZ: "English (Belize)",
  EN_CA: "English (Canada)",
  EN_GB: "English (United Kingdom)",
  EN_IE: "English (Ireland)",
  EN_JM: "English (Jamaica)",
  EN_NZ: "English (New Zealand)",
  EN_PH: "English (Philippines)",
  EN_TT: "English (Trinidad)",
  EN_US: "English (United States)",
  EN_ZA: "English (South Africa)",
  EN_ZW: "English (Zimbabwe)",
  EO: "Esperanto",
  ES: "Spanish",
  ES_AR: "Spanish (Argentina)",
  ES_BO: "Spanish (Bolivia)",
  ES_CL: "Spanish (Chile)",
  ES_CO: "Spanish (Colombia)",
  ES_CR: "Spanish (Costa Rica)",
  ES_DO: "Spanish (Dominican Republic)",
  ES_EC: "Spanish (Ecuador)",
  ES_ES: "Spanish (España)",
  ES_GT: "Spanish (Guatemala)",
  ES_HN: "Spanish (Honduras)",
  ES_MX: "Spanish (Mexico)",
  ES_NI: "Spanish (Nicaragua)",
  ES_PA: "Spanish (Panama)",
  ES_PE: "Spanish (Peru)",
  ES_PR: "Spanish (Puerto Rico)",
  ES_PY: "Spanish (Paraguay)",
  ES_SV: "Spanish (El Salvador)",
  ES_US: "Spanish (United States)",
  ES_UY: "Spanish (Uruguay)",
  ES_VE: "Spanish (Venezuela)",
  ET: "Estonian",
  EU: "Basque",
  FA: "Farsi",
  FI: "Finnish",
  FJ: "Fiji",
  FO: "Faeroese",
  FR: "French",
  FR_BE: "French (Belgium)",
  FR_CA: "French (Canada)",
  FR_CH: "French (Switzerland)",
  FR_LU: "French (Luxembourg)",
  FR_MC: "French (Monaco)",
  FY: "Frisian",
  GA: "Irish",
  GD: "Gaelic",
  GL: "Galician",
  GN: "Guarani",
  GU: "Gujarati",
  HA: "Hausa",
  HE: "Hebrew",
  HI: "Hindi",
  HR: "Croatian",
  HU: "Hungarian",
  HY: "Armenian",
  IA: "Interlingua",
  ID: "Indonesian",
  IE: "Interlingue",
  IK: "Inupiak",
  IN: "Indonesian",
  IS: "Icelandic",
  IT: "Italian",
  IT_CH: "Italian (Switzerland)",
  IW: "Hebrew",
  JA: "Japanese",
  JI: "Yiddish",
  JW: "Javanese",
  KA: "Georgian",
  KK: "Kazakh",
  KL: "Greenlandic",
  KM: "Cambodian",
  KN: "Kannada",
  KO: "Korean",
  KOK: "Konkani",
  KS: "Kashmiri",
  KU: "Kurdish",
  KY: "Kirghiz",
  KZ: "Kyrgyz",
  LA: "Latin",
  LN: "Lingala",
  LO: "Laothian",
  LS: "Slovenian",
  LT: "Lithuanian",
  LV: "Latvian",
  MG: "Malagasy",
  MI: "Maori",
  MK: "FYRO Macedonian",
  ML: "Malayalam",
  MN: "Mongolian",
  MO: "Moldavian",
  MR: "Marathi",
  MS: "Malay",
  MT: "Maltese",
  MY: "Burmese",
  NA: "Nauru",
  NB_NO: "Norwegian (Bokmal)",
  NE: "Nepali (India)",
  NL: "Dutch",
  NL_BE: "Dutch (Belgium)",
  NN_NO: "Norwegian",
  NO: "Norwegian (Bokmal)",
  OC: "Occitan",
  OM: "(Afan)/Oromoor/Oriya",
  OR: "Oriya",
  PA: "Punjabi",
  PL: "Polish",
  PS: "Pashto/Pushto",
  PT: "Portuguese",
  PT_BR: "Portuguese (Brazil)",
  QU: "Quechua",
  RM: "Rhaeto_Romanic",
  RN: "Kirundi",
  RO: "Romanian",
  RO_MD: "Romanian (Moldova)",
  RU: "Russian",
  RU_MD: "Russian (Moldova)",
  RW: "Kinyarwanda",
  SA: "Sanskrit",
  SB: "Sorbian",
  SD: "Sindhi",
  SG: "Sangro",
  SH: "Serbo_Croatian",
  SI: "Singhalese",
  SK: "Slovak",
  SL: "Slovenian",
  SM: "Samoan",
  SN: "Shona",
  SO: "Somali",
  SQ: "Albanian",
  SR: "Serbian",
  SS: "Siswati",
  ST: "Sesotho",
  SU: "Sundanese",
  SV: "Swedish",
  SV_FI: "Swedish (Finland)",
  SW: "Swahili",
  SX: "Sutu",
  SYR: "Syriac",
  TA: "Tamil",
  TE: "Telugu",
  TG: "Tajik",
  TH: "Thai",
  TI: "Tigrinya",
  TK: "Turkmen",
  TL: "Tagalog",
  TN: "Tswana",
  TO: "Tonga",
  TR: "Turkish",
  TS: "Tsonga",
  TT: "Tatar",
  TW: "Twi",
  UK: "Ukrainian",
  UR: "Urdu",
  US: "English",
  UZ: "Uzbek",
  VI: "Vietnamese",
  VO: "Volapuk",
  WO: "Wolof",
  XH: "Xhosa",
  YI: "Yiddish",
  YO: "Yoruba",
  ZH: "Chinese",
  ZH_CN: "Chinese (China)",
  ZH_HK: "Chinese (Hong Kong SAR)",
  ZH_MO: "Chinese (Macau SAR)",
  ZH_SG: "Chinese (Singapore)",
  ZH_TW: "Chinese (Taiwan)",
  ZU: "Zulu"
)

