# xam
# ===
# STRINGS CONSTANTS

const
  # SPECIAL
  STRINGS_EMPTY*: string = ""
  STRINGS_EOL*: string = "\p" # see https://nim-lang.org/docs/manual.html#lexical-analysis-string-literals
  STRINGS_TAB*: string = "\t"
  STRINGS_LF*: string = "\n"
  STRINGS_CR*: string = "\r"
  STRINGS_SPACE*: string = " "

  # SYMBOLS
  STRINGS_BACKTICK*: string = "`"
  STRINGS_DIAERESIS*: string = "¨"
  STRINGS_EQUAL*: string = "="
  STRINGS_NUMERAL*: string = "#"
  STRINGS_PIPE*: string = "|"
  STRINGS_MINUS*: string = "-"
  STRINGS_PLUS*: string = "+"
  STRINGS_PERCENT*: string = "%"
  STRINGS_DOLLAR*: string = "$"
  STRINGS_SLASH*: string = "/"
  STRINGS_BACKSLASH*: string = "\\"
  STRINGS_AMPERSAND*: string = "&"
  STRINGS_ASTERISK*: string = "*"
  STRINGS_UNDERSCORE*: string = "_"
  STRINGS_COLON*: string = ":"
  STRINGS_SEMICOLON*: string = ";"
  STRINGS_COMMA*: string = ","
  STRINGS_PERIOD*: string = "."
  STRINGS_APOSTROPHE*: string = "'"
  STRINGS_QUOTE*: string = "\""
  STRINGS_CARET*: string = "^"
  STRINGS_TILDE*: string = "~"
  STRINGS_AT*: string = "@"
  STRINGS_EXCLAMATION*: string = "!"
  STRINGS_QUESTION*: string = "?"
  STRINGS_INVERTED_EXCLAMATION*: string = "¡"
  STRINGS_INVERTED_QUESTION*: string = "¿"
  STRINGS_DEGREE*: string = "°"
  STRINGS_COPYRIGHT*: string = "©"
  STRINGS_REGISTERED*: string = "®"
  STRINGS_TRADEMARK*: string = "™"
  STRINGS_BULLET*: string = "•"
  STRINGS_PILCROW*: string = "¶"
  STRINGS_SECTION*: string = "§"
  STRINGS_MINOR*: string = "<"
  STRINGS_MAJOR*: string = ">"
  STRINGS_BRACES_OPEN*: string = "{"
  STRINGS_BRACES_CLOSE*: string = "}"
  STRINGS_BRACKETS_OPEN*: string = "["
  STRINGS_BRACKETS_CLOSE*: string = "]"
  STRINGS_PARENTHESES_OPEN*: string = "("
  STRINGS_PARENTHESES_CLOSE*: string = ")"
  
  # NUMBERS
  STRINGS_NUMBER_ZERO*: string = "0"
  STRINGS_NUMBER_ONE*: string = "1"
  STRINGS_NUMBER_TWO*: string = "2"
  STRINGS_NUMBER_THREE*: string = "3"
  STRINGS_NUMBER_FOUR*: string = "4"
  STRINGS_NUMBER_FIVE*: string = "5"
  STRINGS_NUMBER_SIX*: string = "6"
  STRINGS_NUMBER_SEVEN*: string = "7"
  STRINGS_NUMBER_EIGHT*: string = "8"
  STRINGS_NUMBER_NINE*: string = "9"
  
  # UPPERCASE LETTERS
  STRINGS_UPPERCASE_A*: string = "A"
  STRINGS_UPPERCASE_B*: string = "B"
  STRINGS_UPPERCASE_C*: string = "C"
  STRINGS_UPPERCASE_D*: string = "D"
  STRINGS_UPPERCASE_E*: string = "E"
  STRINGS_UPPERCASE_F*: string = "F"
  STRINGS_UPPERCASE_G*: string = "G"
  STRINGS_UPPERCASE_H*: string = "H"
  STRINGS_UPPERCASE_I*: string = "I"
  STRINGS_UPPERCASE_J*: string = "J"
  STRINGS_UPPERCASE_K*: string = "K"
  STRINGS_UPPERCASE_L*: string = "L"
  STRINGS_UPPERCASE_M*: string = "M"
  STRINGS_UPPERCASE_N*: string = "N"
  STRINGS_UPPERCASE_O*: string = "O"
  STRINGS_UPPERCASE_P*: string = "P"
  STRINGS_UPPERCASE_Q*: string = "Q"
  STRINGS_UPPERCASE_R*: string = "R"
  STRINGS_UPPERCASE_S*: string = "S"
  STRINGS_UPPERCASE_T*: string = "T"
  STRINGS_UPPERCASE_U*: string = "U"
  STRINGS_UPPERCASE_V*: string = "V"
  STRINGS_UPPERCASE_W*: string = "W"
  STRINGS_UPPERCASE_X*: string = "X"
  STRINGS_UPPERCASE_Y*: string = "Y"
  STRINGS_UPPERCASE_Z*: string = "Z"

  # LOWERCASE LETTERS
  STRINGS_LOWERCASE_A*: string = "a"
  STRINGS_LOWERCASE_B*: string = "b"
  STRINGS_LOWERCASE_C*: string = "c"
  STRINGS_LOWERCASE_D*: string = "d"
  STRINGS_LOWERCASE_E*: string = "e"
  STRINGS_LOWERCASE_F*: string = "f"
  STRINGS_LOWERCASE_G*: string = "g"
  STRINGS_LOWERCASE_H*: string = "h"
  STRINGS_LOWERCASE_I*: string = "i"
  STRINGS_LOWERCASE_J*: string = "j"
  STRINGS_LOWERCASE_K*: string = "k"
  STRINGS_LOWERCASE_L*: string = "l"
  STRINGS_LOWERCASE_M*: string = "m"
  STRINGS_LOWERCASE_N*: string = "n"
  STRINGS_LOWERCASE_O*: string = "o"
  STRINGS_LOWERCASE_P*: string = "p"
  STRINGS_LOWERCASE_Q*: string = "q"
  STRINGS_LOWERCASE_R*: string = "r"
  STRINGS_LOWERCASE_S*: string = "s"
  STRINGS_LOWERCASE_T*: string = "t"
  STRINGS_LOWERCASE_U*: string = "u"
  STRINGS_LOWERCASE_V*: string = "v"
  STRINGS_LOWERCASE_W*: string = "w"
  STRINGS_LOWERCASE_X*: string = "x"
  STRINGS_LOWERCASE_Y*: string = "y"
  STRINGS_LOWERCASE_Z*: string = "z"

const
  STRINGS*: tuple = (
    EMPTY: STRINGS_EMPTY,
    EOL: STRINGS_EOL,
    TAB: STRINGS_TAB,
    LF: STRINGS_LF,
    CR: STRINGS_CR,
    SPACE: STRINGS_SPACE,
    EQUAL: STRINGS_EQUAL,
    NUMERAL: STRINGS_NUMERAL,
    PIPE: STRINGS_PIPE,
    MINUS: STRINGS_MINUS,
    PLUS: STRINGS_PLUS,
    PERCENT: STRINGS_PERCENT,
    DOLLAR: STRINGS_DOLLAR,
    SLASH: STRINGS_SLASH,
    BACKSLASH: STRINGS_BACKSLASH,
    AMPERSAND: STRINGS_AMPERSAND,
    ASTERISK: STRINGS_ASTERISK,
    UNDERSCORE: STRINGS_UNDERSCORE,
    COLON: STRINGS_COLON,
    SEMICOLON: STRINGS_SEMICOLON,
    COMMA: STRINGS_COMMA,
    PERIOD: STRINGS_PERIOD,
    APOSTROPHE: STRINGS_APOSTROPHE,
    QUOTE: STRINGS_QUOTE,
    CARET: STRINGS_CARET,
    TILDE: STRINGS_TILDE,
    AT: STRINGS_AT,
    EXCLAMATION: STRINGS_EXCLAMATION,
    QUESTION: STRINGS_QUESTION,
    INVERTED_EXCLAMATION: STRINGS_INVERTED_EXCLAMATION,
    INVERTED_QUESTION: STRINGS_INVERTED_QUESTION,
    DEGREE: STRINGS_DEGREE,
    COPYRIGHT: STRINGS_COPYRIGHT,
    REGISTERED: STRINGS_REGISTERED,
    TRADEMARK: STRINGS_TRADEMARK,
    BULLET: STRINGS_BULLET,
    PILCROW: STRINGS_PILCROW,
    SECTION: STRINGS_SECTION,
    MINOR: STRINGS_MINOR,
    MAJOR: STRINGS_MAJOR,
    BRACES_OPEN: STRINGS_BRACES_OPEN,
    BRACES_CLOSE: STRINGS_BRACES_CLOSE,
    BRACKETS_OPEN: STRINGS_BRACKETS_OPEN,
    BRACKETS_CLOSE: STRINGS_BRACKETS_CLOSE,
    PARENTHESES_OPEN: STRINGS_PARENTHESES_OPEN,
    PARENTHESES_CLOSE: STRINGS_PARENTHESES_CLOSE,
    NUMBER_ZERO: STRINGS_NUMBER_ZERO,
    NUMBER_ONE: STRINGS_NUMBER_ONE,
    NUMBER_TWO: STRINGS_NUMBER_TWO,
    NUMBER_THREE: STRINGS_NUMBER_THREE,
    NUMBER_FOUR: STRINGS_NUMBER_FOUR,
    NUMBER_FIVE: STRINGS_NUMBER_FIVE,
    NUMBER_SIX: STRINGS_NUMBER_SIX,
    NUMBER_SEVEN: STRINGS_NUMBER_SEVEN,
    NUMBER_EIGHT: STRINGS_NUMBER_EIGHT,
    NUMBER_NINE: STRINGS_NUMBER_NINE,
    UPPERCASE_A: STRINGS_UPPERCASE_A,
    UPPERCASE_B: STRINGS_UPPERCASE_B,
    UPPERCASE_C: STRINGS_UPPERCASE_C,
    UPPERCASE_D: STRINGS_UPPERCASE_D,
    UPPERCASE_E: STRINGS_UPPERCASE_E,
    UPPERCASE_F: STRINGS_UPPERCASE_F,
    UPPERCASE_G: STRINGS_UPPERCASE_G,
    UPPERCASE_H: STRINGS_UPPERCASE_H,
    UPPERCASE_I: STRINGS_UPPERCASE_I,
    UPPERCASE_J: STRINGS_UPPERCASE_J,
    UPPERCASE_K: STRINGS_UPPERCASE_K,
    UPPERCASE_L: STRINGS_UPPERCASE_L,
    UPPERCASE_M: STRINGS_UPPERCASE_M,
    UPPERCASE_N: STRINGS_UPPERCASE_N,
    UPPERCASE_O: STRINGS_UPPERCASE_O,
    UPPERCASE_P: STRINGS_UPPERCASE_P,
    UPPERCASE_Q: STRINGS_UPPERCASE_Q,
    UPPERCASE_R: STRINGS_UPPERCASE_R,
    UPPERCASE_S: STRINGS_UPPERCASE_S,
    UPPERCASE_T: STRINGS_UPPERCASE_T,
    UPPERCASE_U: STRINGS_UPPERCASE_U,
    UPPERCASE_V: STRINGS_UPPERCASE_V,
    UPPERCASE_W: STRINGS_UPPERCASE_W,
    UPPERCASE_X: STRINGS_UPPERCASE_X,
    UPPERCASE_Y: STRINGS_UPPERCASE_Y,
    UPPERCASE_Z: STRINGS_UPPERCASE_Z,
    LOWERCASE_A: STRINGS_LOWERCASE_A,
    LOWERCASE_B: STRINGS_LOWERCASE_B,
    LOWERCASE_C: STRINGS_LOWERCASE_C,
    LOWERCASE_D: STRINGS_LOWERCASE_D,
    LOWERCASE_E: STRINGS_LOWERCASE_E,
    LOWERCASE_F: STRINGS_LOWERCASE_F,
    LOWERCASE_G: STRINGS_LOWERCASE_G,
    LOWERCASE_H: STRINGS_LOWERCASE_H,
    LOWERCASE_I: STRINGS_LOWERCASE_I,
    LOWERCASE_J: STRINGS_LOWERCASE_J,
    LOWERCASE_K: STRINGS_LOWERCASE_K,
    LOWERCASE_L: STRINGS_LOWERCASE_L,
    LOWERCASE_M: STRINGS_LOWERCASE_M,
    LOWERCASE_N: STRINGS_LOWERCASE_N,
    LOWERCASE_O: STRINGS_LOWERCASE_O,
    LOWERCASE_P: STRINGS_LOWERCASE_P,
    LOWERCASE_Q: STRINGS_LOWERCASE_Q,
    LOWERCASE_R: STRINGS_LOWERCASE_R,
    LOWERCASE_S: STRINGS_LOWERCASE_S,
    LOWERCASE_T: STRINGS_LOWERCASE_T,
    LOWERCASE_U: STRINGS_LOWERCASE_U,
    LOWERCASE_V: STRINGS_LOWERCASE_V,
    LOWERCASE_W: STRINGS_LOWERCASE_W,
    LOWERCASE_X: STRINGS_LOWERCASE_X,
    LOWERCASE_Y: STRINGS_LOWERCASE_Y,
    LOWERCASE_Z: STRINGS_LOWERCASE_Z
  )
